name: deploy-book

# execute this workflow automatically when we push to master
on:
  push:
    branches: [ main ]

jobs:

  build_docs_job:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Make JupyterBook docs
        run: |
          jupyter-book build --all ./docs/.

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
